In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.read_excel("FuelConsumptionCo2.xlsx")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200
1,2022,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263
2,2022,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232
3,2022,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242
4,2022,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230


In [52]:
#Remover caracteristicas categoricas
df.drop(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'TRANSMISSION', 'FUELTYPE'], axis=1, inplace=True)
df

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2.4,4,9.9,7.0,8.6,33,200
1,3.5,6,12.6,9.4,11.2,25,263
2,2.0,4,11.0,8.6,9.9,29,232
3,2.0,4,11.3,9.1,10.3,27,242
4,2.0,4,11.2,8.0,9.8,29,230
...,...,...,...,...,...,...,...
940,2.0,4,10.7,7.7,9.4,30,219
941,2.0,4,10.5,8.1,9.4,30,219
942,2.0,4,11.0,8.7,9.9,29,232
943,2.0,4,11.5,8.4,10.1,28,236


In [53]:
#Remover renglones con valores faltantes
df.dropna(inplace=True)
df

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2.4,4,9.9,7.0,8.6,33,200
1,3.5,6,12.6,9.4,11.2,25,263
2,2.0,4,11.0,8.6,9.9,29,232
3,2.0,4,11.3,9.1,10.3,27,242
4,2.0,4,11.2,8.0,9.8,29,230
...,...,...,...,...,...,...,...
940,2.0,4,10.7,7.7,9.4,30,219
941,2.0,4,10.5,8.1,9.4,30,219
942,2.0,4,11.0,8.7,9.9,29,232
943,2.0,4,11.5,8.4,10.1,28,236


In [54]:
X = df.drop('CO2EMISSIONS', axis=1)
y = df['CO2EMISSIONS']

In [55]:
# Division en grupos de entrenamiento(training) y de prueba(testing)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [56]:
#Normalizacion
from sklearn.preprocessing import normalize
X_train_norm = normalize(X_train)
X_test_norm = normalize(X_test)

# Regresion lineal multiple

In [62]:
# Construccion de un modelo de regresion lineal multiple
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train_norm, y_train)

LinearRegression()

In [63]:
# Coeficientes de regresion
print('Intercepto: ', linreg.intercept_)
print('Coeficientes: ', linreg.coef_)

Intercepto:  388.74250128235667
Coeficientes:  [-116.50352944  111.94245879  -28.55294687  -57.30206895  329.02984369
 -281.56796432]


In [81]:
valores_x = X.iloc[0]

intercepto = linreg.intercept_
coeficientes = linreg.coef_

In [82]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-6588.970957818888)

In [12]:
# Predicciones
y_pred = linreg.predict(X_test_norm)
y_pred

array([242.05056484, 313.42558914, 313.48838497, 250.08779357,
       268.74965249, 210.50834944, 268.07050854, 175.86564657,
       255.97184449, 292.29252653, 132.45443294, 266.48524379,
       243.4632638 , 200.16986777, 263.77265219, 209.23127096,
       282.57265984, 203.26463198, 185.12727518, 300.69297149,
       335.3267567 , 183.6514229 , 377.36202361, 339.22374611,
       268.07050854, 217.69173134, 356.57217613, 360.97835427,
       167.01216892, 333.3653351 , 305.26219156, 239.96354809,
       286.50756304, 237.21125781, 211.02897624, 192.64050467,
       176.39865173, 365.80530797, 359.12417466, 235.32432818,
       231.90736269, 292.76633292, 331.63311108, 168.44837239,
       264.57589623, 209.47811931, 232.04193336, 334.8798269 ,
       358.74392968, 289.9084445 , 161.61005512, 230.51763281,
       297.47314749, 281.5914438 , 419.08030717, 215.21763864,
       177.07211043, 301.38928609, 167.25332091, 321.89888714,
       435.86929512, 291.52669948, 224.32122829, 139.18

In [13]:
# Calculo de indicadores de la bondad de ajuste
from sklearn.metrics import r2_score
from sklearn import metrics

In [14]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9101041999638888
Error absoluto medio:  7.582278595997424
Error cuadratico medio:  311.19797055029375
Raiz del error cuadratico medio:  17.64080413559126


# Ridge

In [15]:
alpha_range = 10.**np.arange(-2, 3)
alpha_range

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [16]:
from sklearn.linear_model import RidgeCV

ridgeregcv = RidgeCV(alphas=alpha_range, scoring='neg_mean_squared_error')
ridgeregcv.fit(X_train_norm, y_train)
ridgeregcv.alpha_

np.float64(0.1)

In [17]:
# Coeficientes de regresion
print('Intercepto: ', ridgeregcv.intercept_)
print('Coeficientes: ', ridgeregcv.coef_)

Intercepto:  370.62064522979716
Coeficientes:  [ -49.94511915   80.3014429   109.58287072   59.01305057   89.25870857
 -265.36368388]


In [69]:
intercepto = ridgeregcv.intercept_
coeficientes = ridgeregcv.coef_

In [70]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-5919.456769450476)

In [71]:
# Predicciones
y_pred = ridgeregcv.predict(X_test_norm)
y_pred

array([243.207916  , 313.14677668, 313.30423144, 250.29296954,
       269.35640365, 210.53248917, 266.44635094, 174.8715644 ,
       255.53956093, 291.1147997 , 131.24617184, 267.12125888,
       243.14749014, 199.28852065, 263.68197064, 208.81457041,
       281.95624325, 202.82287569, 186.25508733, 299.55623607,
       333.81389069, 183.5172903 , 374.52335181, 337.66202676,
       266.44635094, 218.15425036, 355.309407  , 359.64350816,
       166.99834338, 332.44405976, 308.59479151, 240.54143366,
       286.20885598, 236.89118883, 211.45942985, 192.56240732,
       175.39938295, 364.00087486, 360.73786118, 235.46170731,
       233.00383266, 295.1336707 , 332.4642764 , 168.18564129,
       267.67368098, 209.17817347, 232.32445771, 333.5250365 ,
       358.73818421, 289.45652358, 161.60120363, 230.23803067,
       296.545695  , 281.04954218, 418.00548984, 216.18184696,
       177.616426  , 301.14026616, 167.06918565, 319.95604688,
       433.19823889, 290.72767885, 224.22889951, 139.43

In [20]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9127388477539915
Error absoluto medio:  7.450651668123023
Error cuadratico medio:  302.07744383975273
Raiz del error cuadratico medio:  17.38037525025719


# Lasso

In [21]:
from sklearn.linear_model import LassoCV

lassoregcv = LassoCV(n_alphas=100, random_state=1)
lassoregcv.fit(X_train_norm, y_train)
print('Alpha optimo: ', lassoregcv.alpha_)

Alpha optimo:  0.085544800184034


In [22]:
# Coeficientes de regresion
print('Intercepto: ', lassoregcv.intercept_)
print('Coeficientes: ', lassoregcv.coef_)

Intercepto:  424.31751626979326
Coeficientes:  [   0.            0.          137.92132714    0.           63.04551538
 -305.26713558]


In [72]:
intercepto = lassoregcv.intercept_
coeficientes = lassoregcv.coef_

In [73]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-7741.885387043674)

In [74]:
# Prediccion con Alpha optimo
y_pred = lassoregcv.predict(X_test_norm)
y_pred

array([244.2242231 , 310.6909983 , 309.39998916, 249.46182267,
       268.26866578, 211.59162365, 263.37296674, 175.60497434,
       253.56028493, 289.43435264, 136.94387132, 266.03381349,
       243.78672994, 199.49666249, 262.14280384, 209.53396852,
       280.40602104, 201.8903316 , 187.96147316, 298.49678733,
       331.45290308, 186.00591311, 372.89346857, 336.01221889,
       263.37296674, 219.29391693, 353.27698103, 358.20149887,
       169.57711783, 331.4564989 , 312.22965224, 241.292069  ,
       283.30734907, 233.56814795, 211.16886664, 194.39391631,
       176.66591643, 364.09645911, 365.86765931, 236.43642546,
       235.85304174, 296.03356702, 331.57509548, 170.65387117,
       266.6354503 , 210.42175783, 230.19235036, 330.17131673,
       358.38380026, 287.47805309, 165.21837433, 227.19371841,
       294.211036  , 279.78001071, 425.98987798, 215.89426522,
       180.71786506, 300.50500293, 170.19669739, 319.05733349,
       438.46167237, 287.33748116, 225.95399895, 144.96

In [25]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9067951896584938
Error absoluto medio:  7.453202795795379
Error cuadratico medio:  322.65298058585995
Raiz del error cuadratico medio:  17.962543822795812
